# Generated by Django 4.2.1 on 2023-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RsvpResponse",
            fields=[
                (
                    "openid",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("participate", models.BooleanField()),
                ("plusOne", models.BooleanField()),
                ("needHotel", models.BooleanField()),
                ("needHotelStartDate", models.CharField(max_length=64)),
                ("needHotelEndDate", models.CharField(max_length=64)),
                ("notes", models.TextField()),
            ],
        ),
    ]
