# Generated by Django 4.2.1 on 2023-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsvpresponse",
            name="needHotel",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rsvpresponse",
            name="participate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rsvpresponse",
            name="plusOne",
            field=models.BooleanField(default=False),
        ),
    ]
