# Generated by Django 4.2.1 on 2023-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_rsvpresponse_needhotel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuntQuestion",
            fields=[
                (
                    "question_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("question_rich_content", models.TextField()),
                ("answer0", models.CharField(max_length=64)),
                ("answer1", models.CharField(max_length=64)),
                ("answer2", models.CharField(max_length=64)),
                ("answer3", models.CharField(max_length=64)),
                ("correct_answer", models.IntegerField()),
                ("explanation", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UiConfig",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
        ),
    ]
