# Generated by Django 4.2.1 on 2023-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_huntquestion_uiconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuntScore",
            fields=[
                (
                    "openid",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("score", models.IntegerField()),
            ],
        ),
    ]
