# Generated by Django 4.2.1 on 2023-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_huntscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huntscore",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
