# Generated by Django 4.2.3 on 2023-07-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_huntscore_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionKV",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
        ),
    ]
