# Generated by Django 4.2.3 on 2023-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_uiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntscore',
            name='score_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
